### ISSUE TITLE
enoki-jit submodule missing

### ISSUE THREAD

**Issue by will1996** [wjakob/enoki#16]
Hello! 
It appears that enoki-jit has either been removed, or made private in such a way that I am unable to build enoki! 

Forgive me if this is my mistake, I've searched for a few hours on quick fixes, but I don't see any. 

On a recursive submodule pull, I am prompted to log into github, which I don't have the password for, I assume this is because enoki-jit has been made private! 

thanks, 

-Will

**Comment by Speierers** [comment]
Hi @will1996 

Yes, the `enoki-jit` repository has been made private a while ago. This code will be part of a future release of this codebase. In the meantime you will have to stick to official repos:

https://github.com/mitsuba-renderer/mitsuba2/
https://github.com/mitsuba-renderer/enoki
