### ISSUE TITLE
enoki-jit repository no longer exists

### ISSUE THREAD

**Issue by PeterGottesman** [wjakob/enoki#8]
It seems like the enoki-jit repo is a private repo, so this repo can't be cloned/compiled successfully.

**Comment by Speierers** [comment]
Hi @PeterGottesman ,

Indeed, those repositories were made private a few weeks ago. For the reasons, please take a look at the README here:
https://github.com/mitsuba-renderer/mitsuba2/tree/next

**Comment by hellcats** [comment]
Any update on when enoki-git might return?
